"""
API Library
"""

load("@API//library.bzl", "api_library")

api_library(
    name = "api",
        srcs = [
        "src/api.cpp"
    ],
    exported_headers = {
        "api.hpp": "include/api/api.hpp",
        "macros.hpp": "include/api/macros.hpp",
    },
    exported_deps = [
        "SDK//:sdk",
        "StratifyOS//include:sos_include"
    ],
)

